apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-02-07T18:27:21Z"
  labels:
    app: demo-service
  name: demo-service
  namespace: default
  resourceVersion: "33199"
  uid: 7c9ee330-751a-4de8-9e2f-eae6514d58af
spec:
  clusterIP: 10.96.189.112
  clusterIPs:
  - 10.96.189.112
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
